apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multi-source-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: test-1
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: 'https://helm.releases.hashicorp.com'
    chart: hashicorp/vault
    targetRevision: 0.27.0
  - repoURL: 'https://github.com/JWimsingues/argo-helm-fast-poc'
    targetRevision: HEAD
    ref: mycustomvalues.yaml